feat: add frontier wallet
rainbow-me/rainbowkit pull request #1041
Opened 2023-02-21 12:01 UTC by frontierpawan

Official Website:
https://www.frontier.xyz/

Chrome Extension Url:
https://chrome.google.com/webstore/detail/frontier-wallet/kppfdiipphfccemcignhifpjkapfbihd

2023-02-22 19:58 UTC, DanielSinclair commented
Hey @frontierpawan. Please QA with the `rainbowkit-example` Vercel deployment here. Many teams have bumped into different behavior between localhost and a production environment.

2023-02-23 07:00 UTC, DanielSinclair commented
Bumped into an issue where I am unable to connect the wallet after the initial "Deny" reply upon connect prompt. This may be an issue with the wallet's injector; injection is still required for proper detection in RainbowKit.
<img width="1551" alt="Screenshot 2023-02-23 at 1 57 01 AM" src="https://user-images.githubusercontent.com/4412473/220838911-14aa60a1-7100-4e02-81ee-3b912d84563a.png">

2023-03-01 07:31 UTC, punithbm commented
Hi @DanielSinclair, thanks for highlighting. Can you please try now. I have attached the screen recording for the reference. Also note we are using manifest version 3 and have observed some issues with new chrome caching behaviour. But I think it should not change anything w.r.t rainbowkit implementation. Please check and let me know.  

https://user-images.githubusercontent.com/13044958/222072677-0a92bdf0-8d87-4c4f-961f-bb706dcaebbf.mov

2023-03-03 12:14 UTC, punithbm commented
Hi @DanielSinclair , did you get any chance to look into the above comment ?

2023-03-07 05:26 UTC, punithbm commented
@DanielSinclair  Please check this☝️ whenever possible

2023-03-10 02:11 UTC, DanielSinclair commented
@punithbm Seeing a CI error. Please run `pnpm run lint:fix`

2023-03-10 02:15 UTC, DanielSinclair commented
@punithbm Can't seem to get detection working
<img width="1250" alt="Screenshot 2023-03-09 at 9 14 16 PM" src="https://user-images.githubusercontent.com/4412473/224206034-bb59388e-9fd1-4090-abd7-c59258d934b4.png">

2023-03-23 16:29 UTC, DanielSinclair commented
Ran CI tests and a deployment to test against.

2023-04-12 16:26 UTC, DanielSinclair commented
Please reference the discussion here regarding slow injector issues. This is an issue with the wallet injector, and we are holding off an adopting any API changes in RainbowKit for the time being. XDEFI was able to resolve their issue. https://github.com/rainbow-me/rainbowkit/pull/1042#issuecomment-1503783106

2023-04-12 16:38 UTC, DanielSinclair requested changes

2023-04-12 16:38 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/walletConnectors/frontierWallet/frontierWallet.ts
> +  shimDisconnect?: boolean;
Deprecate `shimDisconnect` here

2023-04-12 16:38 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/walletConnectors/frontierWallet/frontierWallet.ts
> +  shimDisconnect,
Reference recent changes to connectors for `options` pass-through https://github.com/rainbow-me/rainbowkit/blob/0d5640929326d65673596a11cd018a9c6524ff8c/packages/rainbowkit/src/wallets/walletConnectors/metaMaskWallet/metaMaskWallet.ts#L31-L34

2023-04-12 16:38 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/walletConnectors/frontierWallet/frontierWallet.ts
> +      }),
Missing `qrCode` and `extension` params https://www.rainbowkit.com/docs/custom-wallets

2023-04-12 16:38 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/walletConnectors/frontierWallet/frontierWallet.svg
Unrounded icons are prefered as RainbowKit will mask

2023-04-12 16:38 UTC, DanielSinclair commented on .changeset/short-follow-clap.md
> +'example': patch
Can remove `example` here

2023-04-12 16:38 UTC, DanielSinclair commented on .changeset/short-follow-clap.md
> +Added support for Frontier wallet
Reference a recent changeset with example wallet usage: https://github.com/rainbow-me/rainbowkit/blob/2b4ede4a1e580c3c3a257f4be4fbb5f14ed3beab/.changeset/many-schools-deliver.md?plain=1#L5-L23

2023-04-19 15:57 UTC, DanielSinclair commented
@frontierpawan Unfortunately am unable to get wallet detection working. This PR is code complete, but will hold-off on merging until that works more reliably. Reference this comment: https://github.com/rainbow-me/rainbowkit/pull/1041#issuecomment-1505573234

2023-05-19 04:32 UTC, punithbm commented
@DanielSinclair  We are able to find a workaround to address the injection detection issue in the Rainbow kit. We have submitted the Chrome build for review, and it might take 3-5 days to go live. Once it is live, we will notify you, and you can proceed with retesting it. Thank you for your continued support and the detailed information provided so far.

2023-05-24 17:24 UTC, punithbm commented
Hi @DanielSinclair  Our extension update is live.  Can you please test in the latest version of the frontier wallet. Version **1.0.20** is working fine with Rainbowkit. Please check and let us know

2023-05-27 04:24 UTC, punithbm commented
Hi @DanielSinclair any update on this ?

2023-05-31 02:23 UTC, punithbm commented
Hi @DanielSinclair  Please check and let us know on this PR ? 

cc: @nickbytes

2023-06-27 11:04 UTC, punithbm commented
@DanielSinclair  any update on when this can be merged ? Please let us know

2023-07-07 06:07 UTC, punithbm commented
@DanielSinclair any update on when this can be merged ? Please let us know

2023-07-13 05:03 UTC, DanielSinclair approved these changes

2023-07-13 05:03 UTC, merged