feat: add TokenPocket wallet
rainbow-me/rainbowkit pull request #1283
Opened 2023-06-09 11:28 UTC by chendatony31

2023-06-15 00:56 UTC, DanielSinclair requested changes

2023-06-15 00:56 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/walletConnectors/tokenPocketWallet/tokenPocketWallet.ts
> +  projectId?: string;
`projectId` is now required after 1.0.2

2023-06-15 00:56 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/walletConnectors/tokenPocketWallet/tokenPocketWallet.ts
> +        'https://chrome.google.com/webstore/detail/tokenpocket/mfgccjchihfkkindfppnaooecgfneiii',
Should use `chrome` instead and provide a fallback site as `browserExtension`

2023-06-15 00:56 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/walletConnectors/tokenPocketWallet/tokenPocketWallet.svg
Please minify, and resize to match the other wallet connectors icons `width="28" height="28" viewBox="0 0 28 28"`. This helps bundle sizes.

2023-06-15 12:09 UTC, chendatony31 commented
Hi, @DanielSinclair  all issues have been fixed.

2023-07-13 05:20 UTC, DanielSinclair approved these changes

2023-07-13 05:20 UTC, merged