feat: cronos blockchain icon
rainbow-me/rainbowkit pull request #1287
Opened 2023-06-12 09:54 UTC by 0xartcro

Added icon for Cronos chain.

2023-06-15 00:50 UTC, DanielSinclair requested changes

2023-06-15 00:50 UTC, DanielSinclair commented on packages/rainbowkit/src/components/RainbowKitProvider/provideRainbowKitChains.ts
> +  | 'cronos'
Missing `cronosTestnet`

2023-06-15 00:50 UTC, DanielSinclair commented on packages/rainbowkit/src/components/RainbowKitProvider/chainIcons/cronos.svg
Icon is missing background color

2023-06-15 00:50 UTC, DanielSinclair commented on packages/rainbowkit/src/components/RainbowKitProvider/chainIcons/cronos.svg
Please also minify and match the svg sizing of the other chain icons. This helps bundle sizes.

2023-06-15 08:07 UTC, 0xartcro commented on packages/rainbowkit/src/components/RainbowKitProvider/chainIcons/cronos.svg
Uploaded new one, let me know if its better now.

> Please also minify and match the svg sizing of the other chain icons. This helps bundle sizes.

2023-06-15 08:46 UTC, 0xartcro commented
Looks like `cronosTestnet` is not present in `wagmi` right now. Created PR there as well https://github.com/wagmi-dev/references/pull/343

2023-06-15 08:46 UTC, 0xartcro commented on packages/rainbowkit/src/components/RainbowKitProvider/provideRainbowKitChains.ts
> +  | 'cronos'
Added, depends on https://github.com/wagmi-dev/references/pull/343

2023-06-22 09:06 UTC, 0xartcro commented
wagmi@1.2.1 has been released which should contain `cronosTestnet` now.

2023-07-05 12:18 UTC, 0xartcro commented
wagmi@1.2.1 has been released which should contain `cronosTestnet` now.

@DanielSinclair This PR is ready to review once again

2023-07-05 17:49 UTC, DanielSinclair commented
@0xartcro Awesome, thanks!

2023-07-06 15:37 UTC, nickbytes approved these changes

2023-07-06 15:57 UTC, DanielSinclair approved these changes

2023-07-06 15:57 UTC, merged