feat: enkrypt wallet support
rainbow-me/rainbowkit pull request #1419
Opened 2023-07-19 22:16 UTC by kvhnuke

Adding Enkrypt wallet support 
please let me know if you see any issues

2023-07-20 00:00 UTC, DanielSinclair requested changes

2023-07-20 03:23 UTC, kvhnuke commented on site/data/docs/custom-wallet-list.mdx
> +
thank  you for the catch, resolved

2023-07-28 04:39 UTC, DanielSinclair commented
While testing, I ran into some issues with the provider. In Safari, I could not seem to trigger a successful injection state. We use the `installed` param in our connector as well as rely on Wagmi connector's `ready` flag [here](https://github.com/wagmi-dev/references/blob/f62be25b5666ede63aa518bb0a3e62432fdacd00/packages/connectors/src/injected.ts#L88). In Chrome, I could successfully injected, but after refreshing the page, the provider would no longer be injected properly and I could not auto-connect or manually connect the wallet again. Try testing against the example deployment here: https://rainbowkit-example-catwn11a6-rainbowdotme.vercel.app/

2023-08-16 18:47 UTC, kvhnuke commented
@DanielSinclair please use 1.25.0 both on Safari and Chrome to test. For Safari please not that you need latest version `16.6`

2023-08-22 06:10 UTC, DanielSinclair approved these changes

2023-08-22 06:10 UTC, merged