feat: `useIsWalletConnectModalOpen` hook
rainbow-me/rainbowkit pull request #1828
Opened 2024-03-05 13:28 UTC by KosmosKey

## Changes
- Exposing `useIsWalletConnectModalOpen` hook to see when the official WalletConnect modal is opened or closed

## What to test
1. Go to [this](https://rainbowkit-example-6gilh3cl5-rainbowdotme.vercel.app/) preview link
2. There should be a small button which says "WalletConnect modal closed" or "WalletConnect modal opened"
![image](https://github.com/rainbow-me/rainbowkit/assets/53529533/989e9fe8-525b-42f6-a5d1-92e69f59eacf)
4. Test on desktop and mobile. Make sure the button displays the correct open / close status of the official WalletConnect modal. Should show "WalletConnect modal closed" if modal is closed and "WalletConnect modal opened" if open.

2024-03-06 06:51 UTC, DanielSinclair requested changes

2024-03-06 06:51 UTC, DanielSinclair commented on packages/rainbowkit/src/components/RainbowKitProvider/WalletConnectProvider.tsx
Are we able to absorb this into `ModalContext` so that we don't need another wrapper provider in the stack?

2024-03-06 15:02 UTC, KosmosKey commented on packages/rainbowkit/src/components/RainbowKitProvider/WalletConnectProvider.tsx
Done 👍

2024-03-07 17:15 UTC, DanielSinclair approved these changes

2024-03-07 17:16 UTC, merged