feat: enhanced provider API / `@tanstack/react-query` peer dependency
rainbow-me/rainbowkit pull request #1934
Opened 2024-04-17 12:50 UTC by magiziz

## Changes
- Added `@tanstack/react-query` as a peer dependency and introduced enhanced provider API.
- Implemented fallback to fetch ENS name from enhanced provider API when mainnet is unavailable.

2024-05-07 06:31 UTC, DanielSinclair commented
@magiziz Noticed the address -> resolved name is a bit slow, even after the first fetch. Seeing a few network requests after leaving the page idle too. Are we taking advantage of react-query caching? https://github.com/rainbow-me/rainbowkit/assets/4412473/307f133e-0b26-49dd-b092-91b215adaf9d

2024-05-07 06:32 UTC, DanielSinclair commented
Also pushed up some tweaks, mainly one that injects the API key at build-time. This can be a bit messy because it also needs to be available within the CI tests (where we can't statically replace the API key). Lmk if you have other thoughts! It will be skipped in CI here because we need to add a new ENV.

2024-05-07 06:38 UTC, DanielSinclair requested changes
When replicating a 401, I noticed we throw console errors and try to re-fetch every few seconds. We should fail more gracefully because we may wind down this API endpoint some day. Max retry should be limited, and we should only need to fetch once at first-render if the caching is working appropriately 
<img width="510" alt="Screenshot 2024-05-07 at 2 36 14 AM" src="https://github.com/rainbow-me/rainbowkit/assets/4412473/f313d6c7-7128-448d-ae65-09b93529e5fb">

2024-05-15 22:30 UTC, magiziz commented on packages/rainbowkit/src/core/network/enhancedProvider.test.ts
> +describe.skip('createHttpClient', () => {
Will do a follow up PR to fix this unit test. Faces issues with github secrets and `process.env`, but we can run this locally for now.

2024-05-17 06:42 UTC, DanielSinclair commented
Force pushed to cleanup the git history here

2024-05-17 07:56 UTC, DanielSinclair approved these changes

2024-05-17 07:59 UTC, merged