feat: add MathWallet
rainbow-me/rainbowkit pull request #570
Opened 2022-07-07 08:29 UTC by mytangying

2022-07-19 22:12 UTC, nickbytes commented
Thanks for the contribution here @mytangying – we're currently discussing out strategy for adding new wallets to the repo and how we can best serve the RainbowKit community while also not being gatekeepers/maintainers of every wallet integration. I'll let you know when we have an update! Thanks for your patience!

2022-08-30 15:29 UTC, 0xzoz commented
@nickbytes is there any update regarding the approach for adding new wallets?

I ask because im one of the Tally Ho community devs helping with integrations. As we ready for DAO launch we would love to have Tally Ho as an option for the awesome Rainbowkit library.

2022-09-06 07:49 UTC, Naxsun commented
Getting added as a wallet connection option would be great. I'm currently in contact with two dapps that are planning to start using Rainbow kit, and would like to add Tally Ho as a specific wallet connection option.

2022-09-12 18:28 UTC, JVK-6935 commented
I came here to signal additional support for Tally Ho wallet.  I just tried connecting with it via Kwenta.io and Lyra on Optimism and it did not work there unlike Curve, Aave, Synthetix, etc. on Optimism that I also use.

2022-09-30 04:17 UTC, markdalgleish commented
@mytangying Sorry for the delay on this, and thanks for the PR!

We've just re-worked RainbowKit internals in v0.7 so that wallets can be imported individually, ensuring our bundle size doesn't keep increasing as we continue to add more wallets.

Are you able to give us write access to your fork so that we can get you updated to the new API and apply some changes before merging?

2022-09-30 04:40 UTC, markdalgleish commented
Also, could you update the logo in this PR so that it's a square rather than including the border radius? We apply a border radius ourselves in the UI and want to be sure it's consistent across all wallets.

2022-09-30 04:41 UTC, markdalgleish commented
@0xzoz We're revisiting the wallet integrations at the moment if you're keen to open a PR.

2022-09-30 04:47 UTC, 0xzoz commented
Cheers @markdalgleish. Let me know if you want me to run through some new docs or just do something similar to this

2022-09-30 05:13 UTC, markdalgleish commented
@0xzoz Our format has changed a bit, but you can reference this PR which I've just migrated to the latest API and conventions: https://github.com/rainbow-me/rainbowkit/pull/550

2022-10-19 18:36 UTC, 0xzoz commented
> @0xzoz Our format has changed a bit, but you can reference this PR which I've just migrated to the latest API and conventions: #550

@markdalgleish added #824 - took longer than expected due to trying to get Tally Ho as a connector in Wagmi

2023-02-07 06:20 UTC, DanielSinclair requested changes

2023-02-07 06:20 UTC, DanielSinclair commented on site/components/Provider/Provider.tsx
> +      wallet.mathwallet({ chains }),
Please revert

2023-02-07 06:20 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/walletConnectors/mathwallet/mathwallet.ts
> +            : undefined,
Missing `qrCode` flag for the WalletConnect flow on Desktop

2023-02-07 06:21 UTC, DanielSinclair commented
Upon review, the WalletConnect flow on Desktop is not functioning as expected. Reference the review
<img width="765" alt="Screenshot 2023-02-07 at 1 18 58 AM" src="https://user-images.githubusercontent.com/4412473/217164073-12a28eb7-d868-4223-b57c-cc9109ee28d8.png">

2023-02-20 06:27 UTC, DanielSinclair commented
Closing for now, but can revisit and reopen if the provider becomes more reliable

2023-02-20 06:27 UTC, closed without merging