docs: update `alchemyId` to `apiKey` to adhere to the new wagmi API
rainbow-me/rainbowkit pull request #623
Opened 2022-07-29 00:04 UTC by Dhaiwat10

Noticed while trying to follow the installation docs that you need to provide an `apiKey` instead of an `alchemyId` in the `configureChains` method now. Updated this in your installation docs.

2022-07-29 06:31 UTC, jxom approved these changes

2022-07-29 06:33 UTC, jxom requested changes
Looks good! We also need to update the "Chains" & "Custom Wallet List" docs with the new usage.

2022-07-29 11:26 UTC, Dhaiwat10 commented
@jxom good catch, done

2022-07-29 14:09 UTC, peduarte approved these changes
excellent stuff frens! <3

2022-08-09 06:11 UTC, jxom approved these changes

2022-08-09 06:11 UTC, merged