Added Safe (Gnosis) connector.
rainbow-me/rainbowkit pull request #806
Opened 2022-10-10 16:57 UTC by stas

We've been having issues recently with WalletConnect so we worked on adding the official Safe connector to our dApp.

Wanted to share the implementation with you guys, hopefully this is useful.

Related convo #348 

---

### On testing the connector

The Safe connector is designed to get activated only when the dApp is loaded directly from the Safe.

![Screenshot 2022-10-10 at 17-51-29 Safe](https://user-images.githubusercontent.com/112147/194916969-cf1f5e22-3b5d-4865-9c05-e22afe3f0db8.png)

In order to enable the auto-connect support, a little trick is required (triggers the Safe connector if it's found):

```diff
+  import { useConnect } from 'wagmi';
+  const { connect, connectors } = useConnect();
+
+  // Auto-connect to Safe if available
+  React.useEffect(() => {
+    const safeConnector = connectors.find((c) => c.id === 'safe' && c.ready);
+
+    if (safeConnector) { connect({ connector: safeConnector }) }
+
+  }, [connect, connectors]);

```

### Custom Safe dApp integration

In order to make it easier to connect to Safe, you can add the dApp to their apps list and access it just as it would be a normal Safe app.

![Screenshot 2022-10-10 at 17-50-39 Safe](https://user-images.githubusercontent.com/112147/194916948-00f2558c-209e-4ed0-bc12-4962e8c6adb0.png)

2022-10-18 15:31 UTC, stas commented
Updated the integration snippet to solve the issue of `safe` auto-connect conflicting with default `autoConnect: true` client config.

2023-01-09 19:37 UTC, gmaijoe commented
this would be great to get in! any chance we can get this merged @RainbowWalletAdmin @rainbow-infra ?

2023-01-21 13:29 UTC, outdoteth commented
Any ETA on this?

2023-01-31 03:34 UTC, benjileibo commented
eta on this?

2023-02-07 17:21 UTC, DanielSinclair requested changes
Please add to `packages/example` for test dApp deployment

2023-02-07 17:21 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/getDefaultWallets.ts
> +        safeWallet({ chains }),
Revert

2023-02-07 17:21 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/getDefaultWallets.ts
> +import { safeWallet } from './walletConnectors/safeWallet/safeWallet';
Revert

2023-02-07 17:21 UTC, DanielSinclair commented on packages/rainbowkit/package.json
> +    "@vanilla-extract/esbuild-plugin": "^2.2.0",
Revert

2023-02-07 17:21 UTC, DanielSinclair commented on packages/rainbowkit/package.json
> +    "@vanilla-extract/private": "^1.0.3",
Revert

2023-02-07 17:21 UTC, DanielSinclair commented on packages/rainbowkit/package.json
> +    "@gnosis.pm/safe-apps-wagmi": "*",
Adopt Wagmi `SafeConnector` instead or discuss differences

2023-02-08 19:00 UTC, benjileibo commented
Wooooooo!!!

2023-02-08 19:00 UTC, stas commented
@DanielSinclair we'd have to bump the wagmi to v0.11, are you guys ok with that? 

The PR should be using the wagmi connectors now btw. I have limited time, so if it's a larger project to update everything to latest wagmi it might take longer to wrap up the PR.

2023-02-08 20:23 UTC, DanielSinclair commented
@stas There are some TypeScript changes, so you can rebase to #1000. That should be merged later today or tomorrow anyway.

2023-02-16 21:02 UTC, benjileibo commented
what happened to this PR @DanielSinclair

2023-02-16 21:36 UTC, DanielSinclair commented
@benjileibo No ETA. Might require larger changes. Working on my own experimental PR at #1028.

2023-02-20 04:18 UTC, DanielSinclair commented
Closing in favor of cherrypicks and additional changes in #1028. The behavior seems to be working as expected but requires additional testing. Feel free to try it out.

2023-02-20 04:18 UTC, closed without merging