feat: add mew wallet
rainbow-me/rainbowkit pull request #916
Opened 2022-12-14 22:07 UTC by jmjles

2022-12-20 19:41 UTC, jmjles commented
@markdalgleish @nickbytes 
This is the new pr for mew wallet. I also made another pr for Enkrypt.

2023-01-27 13:41 UTC, DanielSinclair commented
@jmjles Looks like we're missing `downloadUrls.qrCode`. Most teams point to a redirect catch-all or their landing page download.
<img width="810" alt="Screenshot 2023-01-27 at 8 37 19 AM" src="https://user-images.githubusercontent.com/4412473/215100498-12ef6543-c99a-45b2-b051-5d207e7c404b.png">

2023-01-27 13:46 UTC, DanielSinclair requested changes

2023-01-27 13:46 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/walletConnectors/mewWallet/mewWallet.ts
> +  },
Need `qrCode` here

2023-01-27 13:46 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/walletConnectors/mewWallet/mewWallet.ts
> +  id: 'mewWallet',
For consistency, let's use `mew` as the `id` here

2023-01-27 13:46 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/walletConnectors/mewWallet/mewWallet.ts
> +  name: 'MEW wallet',
Can we replace this with `MEW Wallet` for consistency, or is this the correct brand representation?

2023-01-27 13:52 UTC, DanielSinclair commented
I seem to be unable to connect to WalletConnect via the MEW Wallet app. Is there an alternative path?
![IMG_5768](https://user-images.githubusercontent.com/4412473/215102824-21193bd6-4bd4-4667-99af-3add51c29906.PNG)

2023-02-01 20:05 UTC, gamalielhere commented
@DanielSinclair wallet connect support will be coming this month.

2023-02-15 21:41 UTC, gamalielhere commented
@DanielSinclair it shouldn't need wallet connect actually. You can test this by running the demo locally, accessing MEW wallet, going to the "Browse" feature and accessing the demo via the local network port.

2023-02-15 23:57 UTC, DanielSinclair commented
@gamalielhere CI is failing. Will need you to run a `pnpm lint:fix`

2023-02-16 00:33 UTC, gamalielhere commented
@DanielSinclair pushed those changes

2023-02-16 00:56 UTC, DanielSinclair approved these changes
Working as expected now 👍

2023-03-10 22:44 UTC, closed without merging