feat: add enkrypt wallet
rainbow-me/rainbowkit pull request #917
Opened 2022-12-14 22:25 UTC by jmjles

2023-01-27 14:03 UTC, DanielSinclair commented
Enkrypt is not available as a WalletConnect product, correct? That logic should be stripped. Am also seeing issues with injection detection.
<img width="760" alt="Screenshot 2023-01-27 at 9 00 59 AM" src="https://user-images.githubusercontent.com/4412473/215105427-64186137-e436-4277-bab7-14d057032c0d.png">

2023-01-27 14:05 UTC, DanielSinclair requested changes

2023-01-27 14:05 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/walletConnectors/enkryptWallet/enkryptWallet.ts
> +  const shouldUseWalletConnect = isMobile() && !isEnkryptInjected;
Unnecessary unless a mobile WalletConnect version is available

2023-01-27 14:05 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/walletConnectors/enkryptWallet/enkryptWallet.ts
> +        mobile: {
Should be removed

2023-01-27 14:05 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/walletConnectors/enkryptWallet/enkryptWallet.ts
> +      const connector = shouldUseWalletConnect
Should just return the injected connector here

2023-02-01 22:29 UTC, gamalielhere commented
@DanielSinclair fixed the corrections. Also couldn't replicate the injection issue on my end.

2023-02-01 22:54 UTC, DanielSinclair commented
Still seeing issues on our example dApp deployment: https://rainbowkit-example-73h725g9i-rainbowdotme.vercel.app/
1. Injection not detected
<img width="754" alt="Screenshot 2023-02-01 at 5 52 43 PM" src="https://user-images.githubusercontent.com/4412473/216183933-88e6dfbf-7b72-4532-9a2a-73bae84d2084.png">
2. Multiple connect attempt pop-ups appear on page load and ignore rejects
<img width="1284" alt="Screenshot 2023-02-01 at 5 52 08 PM" src="https://user-images.githubusercontent.com/4412473/216184086-ca567087-f6a2-4a2a-82be-4f4bf79fc0e2.png">

2023-02-20 06:30 UTC, DanielSinclair commented
Closing for now, but can reopen and revisit if the provider and UX becomes more reliable. Working with teams like Phantom, Zerion, and Trust on this and happy to communicate further

2023-02-20 06:30 UTC, closed without merging

2023-02-20 13:21 UTC, jayohTM commented
> Closing for now, but can reopen and revisit if the provider and UX becomes more reliable. Working with teams like Phantom, Zerion, and Trust on this and happy to communicate further

Hi Daniel, I've been tracking this issue and would like to know more about the other wallet integrations.