Added Openblock wallet support
rainbow-me/rainbowkit pull request #920
Opened 2022-12-17 03:54 UTC by Acceyuriko

2023-01-11 16:40 UTC, DanielSinclair requested changes
Thanks for your contribution! Before we review the Openblock connector, please revert changes to `getDefaultWallets`. We have a better solution in the works to resolve the default wallet list issue, and we'd like to solely focus on connector support and stability within RainbowKit.

2023-01-12 07:54 UTC, Acceyuriko commented
> Thanks for your contribution! Before we review the Openblock connector, please revert changes to `getDefaultWallets`. We have a better solution in the works to resolve the default wallet list issue, and we'd like to solely focus on connector support and stability within RainbowKit.

Which commit does `getDefaultWallets` refer to?

2023-01-12 22:48 UTC, DanielSinclair requested changes

2023-01-12 22:48 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/getDefaultWallets.ts
> +        openBlockWallet({ chains }),
@Acceyuriko Referring to this file

2023-02-07 06:48 UTC, DanielSinclair requested changes
Reference the `injectedWallet` connector implementation for an injected-only wallet connector. I tested on mobile and there doesn't appear to be a viable UX. Additionally, am seeing an issue where OpenBlock opens in a new tab on eacg dApp load. This is unexpected behavior that would likely degrade the dApp UX. Can this be corrected on the extension side?

2023-02-07 06:48 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/walletConnectors/openBlockWallet/openBlockWallet.ts
> +        qrCode: shouldUseWalletConnect
Does OpenBlock support WalletConnect? If not, should not use the `qrCode` prop

2023-02-07 06:48 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/walletConnectors/openBlockWallet/openBlockWallet.ts
> +      qrCode: 'https://openblock.com/#/initialize/welcome',
Should remove `android`, `ios`, and `qrCode` props unless there is a mobile app available

2023-02-07 06:48 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/walletConnectors/openBlockWallet/openBlockWallet.ts
> +        mobile: {
Shouldn't use `mobile` unless an app is available

2023-02-08 07:36 UTC, Acceyuriko commented
If I do not set the qrCode props, the modal seems very strange. It will display the contents of the last connector I selected.
![image](https://user-images.githubusercontent.com/7571003/217462808-cd23384f-5d15-4b8a-bba4-75e9e7a0bfab.png)

In addition, OpenBlock is a web wallet rather than a plug-in wallet, so when the page is opened, rainbowkit tries to automatically connect to OpenBlock, which initiates an eth_accounts request and opens the OpenBlock page.

2023-02-08 16:26 UTC, DanielSinclair commented
1. Reference the `injectedWallet` implementation here to prevent modal issues: https://github.com/rainbow-me/rainbowkit/blob/a920c2e92dd6e48effc9b10efe61201ad044a767/packages/rainbowkit/src/wallets/walletConnectors/injectedWallet/injectedWallet.ts#LL11-L32C4
2. It's possible that there isn't an integration path for this particular kind of wallet unless the UX issues can be resolved

2023-02-09 04:03 UTC, Acceyuriko commented
Oh, thats a pitty. Anyway, thanks for the support.

2023-02-09 04:03 UTC, closed without merging