Feat/okxwallet
rainbow-me/rainbowkit pull request #986
Opened 2023-01-30 10:37 UTC by okxwallet

Add okx wallet to rainbow

2023-01-30 17:05 UTC, DanielSinclair requested changes
Would need OKX to be added to `packages/example` for testing. Please revert other additions.

2023-01-30 17:05 UTC, DanielSinclair commented on examples/with-next-custom-button/pages/_app.tsx
> +      okxWallet({ chains }),
Please revert

2023-01-30 17:05 UTC, DanielSinclair commented on examples/with-next-mint-nft/pages/_app.tsx
> +    wallets: [
Please revert

2023-01-30 17:05 UTC, DanielSinclair commented on examples/with-next-siwe-iron-session/pages/_app.tsx
> +      okxWallet({ chains }),
Please revert

2023-01-30 17:05 UTC, DanielSinclair commented on examples/with-next-siwe-next-auth/pages/_app.tsx
> +      okxWallet({ chains }),
Please revert

2023-01-30 17:05 UTC, DanielSinclair commented on packages/example/pages/_app.tsx
> +  okxWallet,
Please revert

2023-01-30 17:05 UTC, DanielSinclair commented on site/components/Provider/Provider.tsx
> +      okxWallet({ chains }),
Please revert

2023-02-03 16:25 UTC, DanielSinclair requested changes

2023-02-03 16:25 UTC, DanielSinclair commented on examples/with-next/pages/_app.tsx
> +      okxWallet({ chains }),
Please revert. For testing, add to `packages/example`

2023-02-07 07:09 UTC, DanielSinclair commented
@okxwallet Am seeing linting errors. Run `pnpm run lint:fix` to resolve. The `rainbowkit-example` will deploy upon the next push.

2023-02-07 17:24 UTC, okxwallet commented
@DanielSinclair lint erros fixed

2023-02-07 17:49 UTC, DanielSinclair requested changes

2023-02-07 17:49 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/walletConnectors/okxWallet/okxWallet.ts
> +      android: 'https://static.byucvwj.cn/upgradeapp/okx-android.apk',
Can we use a Google Play link instead? Or a fallback download landing page? Want to mitigate malicious distributions

2023-02-07 17:53 UTC, DanielSinclair commented
@okxwallet Am seeing a few problems on our test dApp [here](https://rainbowkit-example-1ilqr2ju5-rainbowdotme.vercel.app/)
1. Mobile WalletConnect hangs on scan
![IMG_5827](https://user-images.githubusercontent.com/4412473/217325870-1fdad567-0c0a-4951-ab9b-f206ae5cf596.PNG)
2. Injected provider is not detected on desktop:
https://user-images.githubusercontent.com/4412473/217326420-d5829183-80a8-4d8b-8c1e-f939707687a6.mov

2023-02-08 04:28 UTC, okxwallet commented
@DanielSinclair 
1. I scan wc qr code, it passed, It seems to be network error?
https://user-images.githubusercontent.com/122091289/217433566-1614d796-597f-4ee5-95d8-3e364304ea8f.mp4
2. Injected provider is not detected on desktop
I tested, it passed.
https://user-images.githubusercontent.com/122091289/217433206-a7f0faff-8e7b-414a-a40e-f0636d8b565b.mov

2023-02-08 04:46 UTC, DanielSinclair commented
@okxwallet
1. This is working for me again! ✅
2. Can't seem to get the injector working. A few of the other wallet connectors we are evaluating have run into this issue because they are slow to inject or otherwise executing other work before making `window.ethereum` available to RainbowKit, which detects 'installed' connectors on page load. Could this race condition also affect your wallet extension?

https://user-images.githubusercontent.com/4412473/217435655-b4581d54-e245-4262-876d-f27f3bfe3234.mov

2023-02-08 10:47 UTC, okxwallet commented
@DanielSinclair 
Hi, The wallet inject window.ethereum at 'document_start', It defined by extension rules(https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts).
It can work in my chrome in https://rainbowkit-example-git-fork-okxwallet-feat-c75bd8-rainbowdotme.vercel.app.
Please help me check Chrome Developer Tools have errors and Can you give me the version for okx wallet?
I will let more team members test it.

2023-02-17 01:19 UTC, DanielSinclair commented
@okxwallet The provider isn't detected and I am unable to connect in this test deployment: https://rainbowkit-example-35f7d4fot-rainbowdotme.vercel.app/

2023-02-23 13:42 UTC, okxwallet commented
I test it. The situation you mentioned will indeed happen, not only our wallet, but also the turst wallet. The local environment debugging confirms that there is no problem. Is it possible that it is a problem with the deployment code?

https://user-images.githubusercontent.com/122091289/220924005-a2923e55-4f97-4adf-8bd4-19c3337aacd3.mov

2023-02-23 17:05 UTC, DanielSinclair commented
@okxwallet Chrome treats localhost differently. Confirmed to not be an issue with the deployment.

2023-02-24 05:02 UTC, okxwallet commented
@DanielSinclair Hi
 The trust wallet have the same problem, Do i write the error code? I follow the document add the code.

https://user-images.githubusercontent.com/122091289/221096265-32000de5-b906-4540-8603-0effaac55d77.mov

2023-03-20 15:48 UTC, DanielSinclair requested changes
- M

2023-03-20 15:48 UTC, DanielSinclair commented on packages/rainbowkit/src/wallets/walletConnectors/okxWallet/okxWallet.ts
> +      const getUri = async () => (await connector.getProvider()).connector.uri;
On iOS this URI will default to `wc://` and iOS selects a wallet based on the user's usage pattern. Does OKX have a Deep Link or Universal Link for this pairing flow? We will need to be explicit like so:
```
const getUri = async () => {
   const { uri } = (await connector.getProvider()).connector;
   return isAndroid()
     ? uri
     : `https://rnbwapp.com/wc?uri=${encodeURIComponent(uri)}`;
};
```

2023-03-23 05:40 UTC, DanielSinclair commented
Closing in favor of #1107

2023-03-23 05:40 UTC, closed without merging